### ISSUE TITLE
err 'version is undefined'

### ISSUE THREAD

**Issue by hxj662630** [pangxieju/electron-fix#1]
![image](https://user-images.githubusercontent.com/14244723/111116880-9d497d00-85a1-11eb-9f37-d4792e0299e3.png)
something wrong with 'electron-fix start', bro
'version is undefined'

**Comment by pangxieju** [comment]
Please set the electron version in dependencies and devDependencies in the "package.json" file.

```
// package.json
{
  "dependencies": {
     "electron": "^7.1.7"
  }
}
// or
{
   devDependencies: {
    "electron": "^7.1.7"
  }
}
```
